# Generated by Django 5.1.1 on 2024-10-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volareApp', '0002_aerolinea_imagen_aeropuerto_imagen_pais_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerolinea',
            name='fundacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
