# Generated by Django 4.2.16 on 2024-10-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volareApp', '0004_aerolinea_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerolinea',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
    ]
