# Generated by Django 4.2.16 on 2024-10-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volareApp', '0005_alter_aerolinea_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerolinea',
            name='flota',
            field=models.IntegerField(default=0),
        ),
    ]
