# Generated by Django 4.2.16 on 2024-10-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volareApp', '0006_aerolinea_flota'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='capital',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AddField(
            model_name='pais',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
    ]
