# Generated by Django 5.1.1 on 2024-11-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volareApp', '0007_pais_capital_pais_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerolinea',
            name='aeropuertos',
            field=models.ManyToManyField(related_name='aerolineas', to='volareApp.aeropuerto'),
        ),
    ]
