# Generated by Django 5.1.1 on 2024-11-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volareApp', '0009_alter_pais_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerolinea',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/aerolineas', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/banderas', verbose_name='Image'),
        ),
    ]
