# Generated by Django 5.1.2 on 2024-11-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volareApp', '0010_alter_aerolinea_imagen_alter_pais_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerolinea',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
    ]
