# Generated by Django 5.1.2 on 2024-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volareApp', '0011_alter_aerolinea_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerolinea',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='aeropuerto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Image'),
        ),
    ]
