# Generated by Django 5.1.2 on 2024-12-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volareApp', '0013_alter_pais_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={},
        ),
    ]
